#!/usr/bin/env bash

set -euo pipefail

print_title() {
  local title="$1"
  printf "\033[1;33m"
  printf "%s" "$title"
  printf "\033[0m"
  printf "\n"
}

print_title "Running linter..."
make lint-docker

print_title "Running tests in Vim inside Docker..."
make test-vim-docker

print_title "Running tests in Neovim inside Docker..."
make test-nvim-docker
